name: Check code on pull requests & subsequent pushes

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_USERNAME: codecitizen

jobs:
  owasp:
    name: owasp
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run owasp dependency check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyCheckAnalyze
      - name: Archive owasp check results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: owasp-results
          path: build/reports/dependency-check-report.html
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkMain checkTest
      - name: Archive checkstyle results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: checkstyle-results
          path: build/reports/checkstyle.html
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/reports/tests/test