name: Check code on pull requests & subsequent pushes

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  owasp:
    name: owasp
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
      - name: Run owasp dependency check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dependencyCheckAnalyze
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
      - name: Run checkstyle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkMain checkTest
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
      - name: Run tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test